# Generated by Django 4.2.9 on 2024-01-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkydiveJump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('canopy', models.CharField(max_length=200)),
                ('plane', models.CharField(max_length=200)),
                ('dropzone', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('altitude', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'jump',
            },
        ),
    ]
