# Generated by Django 4.1.7 on 2023-03-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='flights',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.flight'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.passenger'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats_available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='OperatingFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('aircraft', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.aircraft')),
                ('flight', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.flight')),
            ],
        ),
    ]
