# Generated by Django 4.1.7 on 2023-03-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_aircraft_flights_remove_flight_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='citizenship',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
