# Generated by Django 4.1.7 on 2023-03-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_passenger_citizenship'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('flight', 'passenger'), name='unique_flight_passenger'),
        ),
    ]
