# Generated by Django 4.1.7 on 2023-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_ticket_unique_flight_passenger'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='operatingflights',
            constraint=models.UniqueConstraint(fields=('flight', 'aircraft'), name='unique_flight_aircraft'),
        ),
    ]
