# Generated by Django 4.1.7 on 2023-04-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_operatingflights_unique_flight_aircraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineRevenueDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=100)),
                ('revenue', models.IntegerField()),
            ],
        ),
    ]
