# Generated by Django 4.1.7 on 2023-04-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_airlinerevenuedto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='establishedDate',
            new_name='established_date',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='numEmployees',
            new_name='num_employees',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='noGates',
            new_name='no_gates',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='noTerminals',
            new_name='no_terminals',
        ),
    ]
