# Generated by Django 4.1.7 on 2023-04-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_establisheddate_airline_established_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='maxSpeed',
            new_name='max_speed',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='seatingCapacity',
            new_name='seating_capacity',
        ),
    ]
