# Generated by Django 4.1.7 on 2023-04-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_maxspeed_aircraft_max_speed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='operatingflights',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['airline_name'], name='base_aircra_airline_4f2f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_airport', 'arrival_airport'], name='base_flight_departu_a4eaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingflights',
            index=models.Index(fields=['flight', 'aircraft'], name='base_operat_flight__2059d0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['flight', 'passenger'], name='base_ticket_flight__b9a3af_idx'),
        ),
    ]
