# Generated by Django 4.1.7 on 2023-04-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_aircraft_options_alter_flight_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='operating_aircraft',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='base.aircraft'),
        ),
    ]
