# Generated by Django 4.1.7 on 2023-04-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_flight_base_flight_departu_a4eaf3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='operating_aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='base.aircraft'),
        ),
    ]
