# Generated by Django 4.1.7 on 2023-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_flight_operating_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='call_sign',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
