# Generated by Django 4.1.7 on 2023-04-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_flight_call_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='airline_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='base.airline'),
        ),
    ]
