# Generated by Django 4.1.7 on 2023-04-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_ticket_flight_alter_ticket_passenger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_airport', 'id'], name='base_flight_departu_2693d0_idx'),
        ),
    ]
