# Generated by Django 4.1.7 on 2023-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_flight_base_flight_departu_2693d0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
