# Generated by Django 4.1.7 on 2023-05-07 21:58

import base.models.UserProfile
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_passenger_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, max_length=500, validators=[base.models.UserProfile.validate_no_profanity])),
                ('age', models.IntegerField(blank=True, null=True, validators=[base.models.UserProfile.validate_positive])),
                ('gender', models.CharField(blank=True, max_length=1, validators=[base.models.UserProfile.validate_gender])),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('confirmation_code', models.CharField(blank=True, max_length=12)),
                ('confirmation_code_valid_until', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
