# Generated by Django 4.1.7 on 2023-05-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
